project:
  type: website

website:
  title: "Глубинное Обучение на Jax"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/AlexandrByzov
format:
  html:
    theme: lux
    css: styles.css


